backend:
  name: github
  repo: owenhoskins/phenomic-netlify-cms # replace by your repo
  branch: master # replace if you want netlify-cms publish on a different branch

public_folder: "assets/uploads" # The src attribute for uploaded media will begin with /assets/uploads
media_folder: "content/assets/uploads" # Media files will be stored in the repo under content/assets/uploads

# consider using "content/assets/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts" # a subfolder of your public_folder
    create: true
    slug: "{{slug}}"
    sort: "date:desc" # Default is title:asc
    card: {type: "alltype", text: "title"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image", optional: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "Post"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General settings"
        file: "_settings/general.json"
        fields:
          - {label: "Main site title", name: "site_title", widget: "string"}
          - {label: "Number of frontpage posts", name: "post_count", widget: "number"}
          - {label: "Site cover image", name: "cover", widget: "image"}